---

- name: Build
  hosts: all
  become: yes
  tasks:
    - yum: name=cryptsetup
    - yum: name=mdadm
    - yum: name=cloud-utils

    - name: PIP
      shell: curl https://bootstrap.pypa.io/get-pip.py | python
      args:
        creates: /bin/pip

    - name: AWS cli
      shell: pip install awscli
      args:
        creates: /bin/aws

    - name: Download cloudwatch logs agent
      get_url:
        url: https://s3.amazonaws.com//aws-cloudwatch/downloads/latest/awslogs-agent-setup.py
        dest: /tmp/awslogs-agent-setup.py
        mode: "+x"

    - name: Cloudwatch logs config
      copy:
        dest: /tmp/cwlogs.conf
        content: |
          [general]
          state_file = /var/awslogs/state/agent-state

          [/var/log/messages]
          file = /var/log/messages
          log_group_name = /greenplum/system
          log_stream_name = {instance_id}
          datetime_format = %b %d %H:%M:%S

    - name: Install cloudwatch log agent
      environment:
        LC_ALL: C
      shell: /tmp/awslogs-agent-setup.py --region eu-west-2 --non-interactive -c /tmp/cwlogs.conf
      args:
        creates: /var/awslogs/etc/aws.conf

    - name: Copy cloudwatch logs starter
      copy:
        src: startcloudwatchlogs.sh
        dest: /usr/bin/startcloudwatchlogs.sh
        owner: root
        group: root
        mode: 0755

    - name: Make Cron Job to start awslogs with right region
      cron:
        name: Start awslogs
        special_time: reboot
        job: /usr/bin/startcloudwatchlogs.sh

    - name: Bootstrap
      copy:
        src: bootstrap-raid.sh
        dest: /usr/bin/bootstrap-raid.sh
        owner: root
        group: root
        mode: 0755

    - name: Make Cron Job to start bootstrap-raid at boot
      cron:
        name: Start bootstrap
        special_time: reboot
        job: /usr/bin/bootstrap-raid.sh